RubyOnRails_Blog/blog/config/routes.rb
Rails.application.routes.draw do
  root 'mysite#home'
  get 'mysite/home' => 'mysite#home'

  get 'mysite/post_new' => 'mysite#post_new'
  post 'mysite/post_new' => 'mysite#post_new'

  get 'mysite/post_detail' => 'mysite#post_detail'

  get 'mysite/post_edit' => 'mysite#post_edit'
  patch 'mysite/post_update' => 'mysite#post_update'
  get 'mysite/post_delete' => 'mysite#post_delete'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

RubyOnRails_Blog/blog/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

RubyOnRails_Blog/blog/app/models/post.rb
class Post < ApplicationRecord
end

RubyOnRails_Blog/blog/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

RubyOnRails_Blog/blog/app/controllers/mysite_controller.rb
class MysiteController < ApplicationController
  def home
    @posts = Post.all
  end

  def post_new
    if request.post?
      @entry = Post.create({:author => params[:author], :title =>  params[:title], :text =>  params[:text], :created_date => Time.now })
      flash[:success] = 'Post Saved'
      redirect_to(:action => 'home')
    end
  end

  def post_detail
    @post = Post.find(params[:id])
  end

  def post_edit
    @post = Post.find(params[:id])

  end

  def post_update
    @post = Post.find(params[:id])
    @post.update({:author => params[:post][:author], :title =>  params[:post][:title], :text =>  params[:post][:text]})

    if @post.save!
      flash[:success] = 'Post Updated'
      redirect_to(:action => "home")
    else
      render action: 'post_edit'
    end
  end

  def post_delete
    @post = Post.find(params[:id]).destroy
    flash[:success] = 'Post Deleted'
    redirect_to(:action => "home")
  end
end

RubyOnRails_Blog/blog/app/helpers/application_helper.rb
module ApplicationHelper
end

RubyOnRails_Blog/blog/app/helpers/mysite_helper.rb
module MysiteHelper
end

RubyOnRails_Blog/blog/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <%= csrf_meta_tags %>
    <%= favicon_link_tag 'plane.png' %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
  </head>

  <body>
    <nav class="navbar navbar-inverse" style="width: 95%; margin: 0 auto; padding: 5px 5px 5px 5px;">
      <div class="container-fluid">
        <ul class="nav navbar-nav">
          <li><%= link_to 'MyBlog', :controller => "mysite", :action => "home" %></li>
          <li><%= link_to '<i class="glyphicon glyphicon-plus"> NewPost</i>'.html_safe, :controller => "mysite", :action => "post_new" %></li>
        </ul>
      </div>
    </nav>
    <div style="width: 70%; margin: 0 auto"><%= yield %></div>

  </body>
</html>

RubyOnRails_Blog/blog/app/views/mysite/home.html.erb
<h1>Home</h1>
<p>My Blog Posts</p>

<% flash.each do |key, value| %>
    <div class="alert alert-<%= key %>"><%= value %></div>
<% end %>

<table class="table">
  <tr>
    <th>Title</th>
    <th>Author</th>
    <th>Text</th>
  </tr>
  <% @posts.each do |p| %>
      <tr>
        <td><%= link_to p.title, mysite_post_detail_path(:id => p.id) %></td>
        <td><%= p.author %></td>
        <td><%= p.text %></td>
      </tr>
  <% end %>
</table>

RubyOnRails_Blog/blog/app/views/mysite/post_detail.html.erb
<h1>Post Details</h1>
<p>View the details of the selected post</p>


<table class="table">
  <tr>
    <th><%= link_to 'Edit', mysite_post_edit_path(:id => @post.id) %></th>
  </tr>
  <tr>
    <th><%= link_to 'Delete', mysite_post_delete_path(:id => @post.id) %></th>
  </tr>
</table>

<table class="table">
  <tr>
    <td><strong>Title:</strong></td>
    <td><%= @post.title %></td>
  </tr>

  <tr>
    <td><strong>Author:</strong></td>
    <td><%= @post.author %></td>
  </tr>

  <tr>
    <td><strong>Created Date:</strong></td>
    <td><%= @post.created_date %></td>
  </tr>

  <tr>
    <td><strong>Text:</strong></td>
    <td><%= @post.text %></td>
  </tr>
</table>

RubyOnRails_Blog/blog/app/views/mysite/post_edit.html.erb
<h1>Edit Post</h1>
<p>Edit the details of selected post</p>

<% flash.each do |key, value| %>
    <div class="alert alert-<%= key %>"><%= value %></div>
<% end %>

<p>
  <%= link_to 'Delete', mysite_post_delete_path(:id => @post.id) %>
</p>

<%= form_for(@post, :url => {:action => 'post_update', :id => @post.id}) do |p| %>
    <p> Author:
      <%= p.text_field :author %>
    </p>
    <p> Title:
      <%= p.text_field :title %>
    </p>
    <p> Text:
      <%= p.text_area :text %>
    </p>
    <p>
      <%= submit_tag 'Update Post' %>
    </p>
<% end %>

RubyOnRails_Blog/blog/app/views/mysite/post_new.html.erb
<h1>New Blog Post</h1>
<p>Add a new blog post</p>

<% flash.each do |key, value| %>
    <div class="alert alert-<%= key %>"><%= value %></div>
<% end %>

<%= form_tag('post_new', {:method => 'post', remote: true} ) do %>
    <p> Author:
      <%= text_field_tag 'author' %>
    </p>
    <p> Title:
      <%= text_field_tag 'title' %>
    </p>
    <p> Text:
      <%= text_area_tag 'text' %>
    </p>
    <p>
      <%= submit_tag 'Publish Post' %>
    </p>
<% end %>