RubyOnRails_Blog/banko/config/routes.rb
Rails.application.routes.draw do
  get 'other/name'

  get 'other/index'

  get 'other/show'

  get 'other/change'

  get 'other/update'

  get 'other/quote'

  get 'main/welcome'

  get 'main/goodbye'

end

RubyOnRails_Blog/banko/app/models/entry.rb
class Entry < ActiveRecord::Base
end

RubyOnRails_Blog/banko/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

RubyOnRails_Blog/banko/app/controllers/main_controller.rb
class MainController < ApplicationController
  layout 'start_to_end'

  def welcome
	@message = "Welcome"
  end

  def goodbye
    @message = "Goodbye"
	@entries = Entry.all
  end
end

RubyOnRails_Blog/banko/app/controllers/other_controller.rb
class OtherController < ApplicationController

	# MODIFICATION TO THIS METHOD
	def name
		@fname = params[:fst_name]
		@lname = params[:lst_name]
		if !@fname.nil? then @entry = Entry.create({:first_name => @fname, :last_name =>  @lname}) end
	end

	# MODIFICATION TO THIS METHOD
	def index
		@person = Entry.find(params[:id])
		@fname = @person.first_name
		@lname = @person.last_name
		@person.update_attributes({:address => params[:st_name], :salary => params[:salary], :loan => params[:loan], :loan_reason => params[:reason]})
		if !@person.address.nil? then render "show" end
	end

	# MODIFICATION TO THIS METHOD
	def show
		@person = Entry.find(params[:id])
	end

	# MODIFICATION TO THIS METHOD
	def change
		@person = Entry.find(params[:id])
		@fname = @person.first_name
		@lname = @person.last_name
	end

	# NEW METHOD -
	def update
		@person = Entry.find(params[:id])
		@person.update({:salary => params[:salary], :loan => params[:loan]})
		redirect_to other_change_path(:id => @person.id)
	end

	# MODIFICATION TO THIS METHOD
	def quote
		@person = Entry.find(params[:id])
		if !@person.salary.nil? then
			if (@person.salary *  3) < @person.loan
			then @message = "You goddam pauper, you asked us for a loan that is: more than three times your salary. \n Please go back and re-enter your correct salary."
			else  @message = "Sure thing baby..."
			end
		else @message = "Seem to have an empty record??"
		end
	end
end

RubyOnRails_Blog/banko/app/helpers/application_helper.rb
module ApplicationHelper
end

RubyOnRails_Blog/banko/app/helpers/main_helper.rb
module MainHelper
end

RubyOnRails_Blog/banko/app/helpers/other_helper.rb
module OtherHelper
end

RubyOnRails_Blog/banko/app/views/layouts/application.html.erb
<html>
<head><title><%= @message %> </title>
	<%= stylesheet_link_tag 'application' %>
	</head>
<body>
<p align="center">  <font size="7">The Monster & Leinster Bank </font></p>
<p align="center"> <%= image_tag("monster.jpg") %> </p>

<%= yield %>

<p> <font size="1"> Monster & Leinster Inc. accept no responsibility if 
you fall into arrears on your loan and are not responsible for the thugs that will call around 
to your house with baseball bats to help you with your repayment schedule. </font> </p>
</body>
</html>

RubyOnRails_Blog/banko/app/views/layouts/start_to_end.erb
<!DOCTYPE html>
<html>
<head>
  <title> M&L Bank </title>
</head>
<body>

<%= yield %>
<p align="center"> <font size="1"> Monster & Leinster Inc. &copy 2014 </font> </p>

</body>
</html>

RubyOnRails_Blog/banko/app/views/main/goodbye.html.erb
<h1><p align="center"> <%= h @message %> to Monster & Leinster's</h1>

<h1><p align="center"> End Page</h1>

<p align="center"><%= link_to image_tag("monster.jpg"),
															:controller => "main", :action => "welcome" %> </p>

<h5> <p align="center"> [click logo to re-enter site] </p></h5>

<ul>
	<% @entries.each do |entry| %>
			<li> <%=h entry.first_name %>, <%=h entry.last_name %> , <%=h entry.salary %>, <%=h entry.loan %> <%=h entry.id %></li>
	<% end %>
</ul>

RubyOnRails_Blog/banko/app/views/main/welcome.html.erb
<h1><p align="center"> <%= h @message %> to Monster & Leinster's</h1>

<h1><p align="center"> Home Page</h1>

<p align="center"><%= link_to image_tag("monster.jpg"),
															:controller => "other", :action => "name" %> </p>

<h5> <p align="center"> [click logo to enter] </p></h5>

RubyOnRails_Blog/banko/app/views/other/change.html.erb
<h1> <p align="center"> Your Mortgage Details </p></h1>
<p> So, we have your details as: </p>

<p> <b>First Name:</b> <%=h @person.first_name %> </p>
<p> <b>Last Name:</b> <%=h @person.last_name %> </p>
<p> <b>Address:</b> <%=h @person.address %> </p>
<p> <b>Salary:</b><%=h @person.salary %> </p>
<p> <b>Loan:</b> <%=h @person.loan %> </p>
<p> <b>Reason:</b> <%=h @person.loan_reason%> </p
<p> <b>Your ID:</b> <%=h @person.id %>

<p> So, <%= h @fname.capitalize %>, would you like to change your salary and loan amount: </p>
<%= form_tag('update', :url => { :action => 'update' }, :method => 'get') do %>
		<p> Salary:
			<%= text_field_tag 'salary', @person.salary %>
		<p> Loan Amount:
			<%= text_field_tag 'loan', @person.loan %>
			<%= hidden_field_tag :id ,@person.id %>
			<%= submit_tag 'send' %>
<% end %>


<% if @person.salary then %>
		<p> Please
			<%= link_to 'Ask For Quote Again', other_quote_path(:id => @person.id)  %>
<% end %>
or
<%= link_to 'Go Back to Start', other_index_path(:id => @person.id)  %> .

RubyOnRails_Blog/banko/app/views/other/index.html.erb
<h1> <p align="center"> Your Mortgage Details </p></h1>
<p> So, <%= h @fname.capitalize %>, let us get some more of your details: </p>
<p><b>First Name:</b> <%= h @fname.capitalize %> </p>
<p><b>Last Name:</b> <%= h @lname.capitalize %> </p>
<%= form_tag('index', :method => 'get') do %>
		<p> Address:
			<%= text_field_tag 'st_name', @address, :required => true %>
		<p> Salary:
			<%= text_field_tag 'salary', @salary, :required => true %>
		<p> Loan Amount:
			<%= text_field_tag 'loan', @loan, :required => true %>
		<p> Loan Reason:
			<%= text_field_tag 'reason', @loan_reason, :required => true %>
			<%= hidden_field_tag :id ,@person.id%>


			<%= submit_tag 'send'%>
<% end %>

<% if @person.address then %>
		<%=  link_to "show details", other_show_path(:id => @person.id)   %></p>
<% end %>

RubyOnRails_Blog/banko/app/views/other/name.html.erb
<p> We are very pleased to welcome you our home mortgage page. </p>
<p> Please enter your first and last name below: </p>

<%= form_tag("name", :method => 'get') do %>
		<p> First Name:
			<%= text_field_tag 'fst_name', nil, :required => true %>
		<p> Last Name:
			<%= text_field_tag 'lst_name', nil,  :required => true %>
			<%= submit_tag 'send' %>
<% end %>

<% if @fname then %>
		<p> Welcome <%= h @entry.first_name %>, let's go to the
			<%= link_to 'next page', other_index_path(:id => @entry.id)  %>.</p>
<% end %>

RubyOnRails_Blog/banko/app/views/other/quote.html.erb
<h1> <p align="center"> Your Quote </p></h1>

<p>  <%=h @message %> </p>

<p> Would you like to
  <%= link_to 'Finish', main_goodbye_path(:id => @person.id) %> or
  <%= link_to 'Change Details',  other_change_path(:id => @person.id)  %>
</p>

RubyOnRails_Blog/banko/app/views/other/show.html.erb
<h1> <p align="center"> Your Mortgage Details </p></h1>
<p> So, we have your details as: </p>

<p> <b>First Name:</b> <%=h @person.first_name %> </p>
<p> <b>Last Name:</b> <%=h @person.last_name %> </p>
<p> <b>Address:</b> <%=h @person.address %> </p>
<p> <b>Salary:</b><%=h @person.salary %> </p>
<p> <b>Loan:</b> <%=h @person.loan %> </p>
<p> <b>Reason:</b> <%=h @person.loan_reason%> </p>
<p> <b>Your ID:</b> <%=h @person.id %> </p>

<p> Do you want to
  <%= link_to 'Ask For Quote',  other_quote_path(:id => @person.id)   %> or
  <%= link_to 'Go Back', other_index_url(:id => @person.id)  %> . </p>